plugins {
    id 'java'
	id 'antlr'
    id("com.diffplug.spotless") version "7.0.2"
}

description = "Compiler for Basic4GL language"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation('junit:junit:4.12')
    implementation fileTree(dir: "libs", include: "*.jar")
    implementation project(":runtime")
    antlr "org.antlr:antlr4:4.5"
}

spotless {
    java {
        // Use the default importOrder configuration
        importOrder()

        removeUnusedImports()
        palantirJavaFormat('2.50.0').formatJavadoc(false)

        formatAnnotations()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

build.dependsOn spotlessApply

// Miscellaneous tools.

